language: ruby
# Limit ruby versions to latest 1.9 and latest 2.2 to avoid a big build matrix
rvm:
  - 1.9
  - 2.2
# Load database schema before rake
before_script: bundle exec rake db:schema:load
# Test on all supported rails versions
gemfile:
  - gemfiles/activeadmin_master.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
